# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aae9551b85d2f5d23f4d54f9816ee30d9376ef1060d252ab8630dbbc43012d9ed2aad3e8dba2b832fbd678e1505d58085aa13ad067a450d73530313988f6e0e2

test:
  secret_key_base: f216bc5eaad5a7a45fe432430ab9da03dfcfcb348e71b55515de7f98d445101ecf530d0e471327395de6d05075bc96014e7eb0c3fe1b9375eabbf72829cf9a15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
